# Generated by Django 5.1.2 on 2024-10-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('wiek', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('zlecenia', models.TextField()),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodDoctorApp.pacjent')),
            ],
        ),
    ]
